/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        "on-secondary-container": "#d3b07a",
        "surface-container-highest": "#343535",
        "inverse-primary": "#7e5700",
        "surface-container-low": "#1b1c1c",
        "secondary-fixed-dim": "#e5c189",
        "surface-container": "#1f2020",
        "outline": "#9d8f7b",
        "secondary-container": "#5b4216",
        "on-primary-container": "#6c4a00",
        "on-tertiary-container": "#005871",
        "surface-container-high": "#2a2a2a",
        "inverse-on-surface": "#303030",
        "inverse-surface": "#e4e2e2",
        "surface-bright": "#393939",
        "error-container": "#93000a",
        "on-background": "#e4e2e2",
        "on-surface": "#e4e2e2",
        "on-tertiary": "#003546",
        "surface-container-lowest": "#0e0e0e",
        "on-tertiary-fixed-variant": "#004d64",
        "on-primary-fixed": "#281900",
        "tertiary": "#b5e7ff",
        "surface": "#131314",
        "error": "#ffb4ab",
        "secondary-fixed": "#ffdeac",
        "surface-tint": "#fdbb41",
        "outline-variant": "#504535",
        "on-secondary-fixed": "#281900",
        "on-tertiary-fixed": "#001f2a",
        "primary-fixed-dim": "#fdbb41",
        "on-primary": "#432c00",
        "on-secondary-fixed-variant": "#5b4216",
        "background": "#131314",
        "surface-variant": "#343535",
        "on-error": "#690005",
        "on-primary-fixed-variant": "#604100",
        "tertiary-fixed": "#bde9ff",
        "surface-dim": "#131314",
        "tertiary-container": "#59d1ff",
        "primary-fixed": "#ffdeac",
        "tertiary-fixed-dim": "#65d3ff",
        "on-surface-variant": "#d5c4ae",
        "secondary": "#e5c189",
        "on-error-container": "#ffdad6",
        "on-secondary": "#422c02",
        "primary": "#ffdaa3",
        "primary-container": "#fab83e"
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
        manrope: ["Manrope", "sans-serif"],
        inter: ["Inter", "sans-serif"],
      },
      borderRadius: {
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [],
}

